### ISSUE TITLE
Her må vi programmere

### ISSUE THREAD

**Issue by EHelgeland** [freianes/Vinterhage#1]

**Comment by freianes** [comment]
Denon 2807 (Volumstyring) (Source)
Sony projektor (inngang C)
RMC3
Tsw 752
Rele 1 og 2 for lerret styring (på rmc3) - (230v - 24v rele)

Kilde: (Lyd bilde)
1 - Chromecast
2 - Playstation / Nintendo Switvh

KIlde: (Lyd)
Chromecast audio, uten og starte projektor og ta ned lerret.

2 startup?


Iphone Applikasjon

**Comment by freianes** [comment]
status?
@EHelgeland

**Comment by EHelgeland** [comment]
Waiting on customer
@freianes

**Comment by EHelgeland** [comment]
Kan vi få en oppdatering i denne saken?
@freianes 
@EHelgeland

**Comment by EHelgeland** [comment]
nvm
