### ISSUE TITLE
Styring

### ISSUE THREAD

**Issue by EHelgeland** [freianes/Vinterhage#4]
Styres Denon via IR?
Styres Projektor via IP eller COM?
Ønsker du 40s holdetid på lerret-relè?

**Comment by EHelgeland** [comment]
@freianes

**Comment by freianes** [comment]
@EHelgeland 
Denon via RS232 (com)
Projektor (com)
40s holdetid er sikkert fint.
OBS. utfordringen med det gamle programmet er at lerret henger seg og kjører "opp" og "ned" på likt av og til.
